### ISSUE TITLE
v2.0.2 introduced some bad typo

### ISSUE THREAD

**Issue by shustariov-andrey** [kisenka/svg-sprite-loader#103]
https://github.com/kisenka/svg-sprite-loader/blob/v2.0.2/examples/browser-sprite/build/main.js#L600

window.localtion.href - should be window.location.href

**Comment by shustariov-andrey** [comment]
My bad, actually, it is there since the beginning

**Comment by kisenka** [comment]
Fixed in `svg-baker-runtime@1.2.93`, please update

**Comment by shustariov-andrey** [comment]
Didn't help. Still seeing broken browser-sprite.build.js in svg-sprite-loader/runtime folder. Did rm -Rf node_modules and npm i. Used "svg-sprite-loader": "2.1.0-2"

**Comment by kisenka** [comment]
Pinged you in hanguots

**Comment by kisenka** [comment]
Fixed in `svg-sprite-loader@2.1.0`

**Comment by shustariov-andrey** [comment]
Yep, can confirm the fix, thanks!
