### ISSUE TITLE
Syles attributes overwritten due to multiple svg exported with style tags and same class names

### ISSUE THREAD

**Issue by andreacab** [kisenka/svg-sprite-loader#69]
Hi, 

Not sure the title explains it well, so here a screenshot to help:

As you can see, the two expanded symbol -> defs -> style tag have the same class names. Therefore when the designer/frontend dev is tweaking the attributes in the style tag of the last svg required, it overwrites all the previous ones.  

![screen shot 2016-11-24 at 4 30 16 pm](https://cloud.githubusercontent.com/assets/3372323/20611640/5b758768-b263-11e6-9eb5-6c4eb33795c7.png)

There are different ways to tackle that issue that I know of. Having a lot of svgs and not being in contact with the designer, I am looking for a solution with this loader. Would that be interesting? Can the loader do it already (from my current understanding, it can't)? Am I the only one with that issue? I have some time to help with a PR if that can help.

Thanks for your answer, and thanks for that great loader!

**Comment by JimmyMultani** [comment]
Seconded, we're using an open source library of emojis and running into this issue as well.

Maybe we can have the id/class cleaned up (either through prefixing or adding a unique identifier) before injecting onto the page?

**Comment by princed** [comment]
> Can the loader do it already?

You're quite right, unfortunately it can't at the moment.


> Am I the only one with that issue? I have some time to help 

> Maybe we can have the id/class cleaned up (either through prefixing or adding a unique identifier) before injecting onto the page?
Seems, there's some demand. And we'd love to see a PR fixing this issue.

**Comment by kisenka** [comment]
@andreacab thanks for your suggestion, PR is always welcome!

> Can the loader do it already (from my current understanding, it can't)?

You're right, the loader can't do that now, but it can be implemented (see [lib/processings/prefixize.js](https://github.com/kisenka/svg-sprite-loader/blob/master/lib/processings/prefixize.js)). Please use pure CSS-parser instead of regexes (PostCSS for example).

**Comment by andreacab** [comment]
@kisenka cool thx for the info, will give it a try

**Comment by briantobo** [comment]
Hi !
I updated my project to use svg-sprite-loader 2.0 and it seems to break this functionality.
Is there an option to set in the webpack config to enable it again?

Thanks

**Comment by kisenka** [comment]
@briantobo oh, looks like I forgot to move this feature in 2.0. Will fix this today, stay tuned and thanks for reporting!

**Comment by kisenka** [comment]
@briantobo please update your dependencies (`npm update` or `yarn upgrade`), the issue should be fixed.

**Comment by briantobo** [comment]
Hi again and thank you for the very quick response.
I updated to version 2.0.3 but they generated SVG still doesn't have the styles prefixed like version 0.3.1. Should they be by default? I'm not passing any option to the loader in the webpack config at the moment.

Have a nice day,
Thomas

**Comment by kisenka** [comment]
@briantobo all manipulations with svg made by [svg-baker](https://github.com/kisenka/svg-baker). I've added TravisCI build, you need [this test](https://github.com/kisenka/svg-baker/blob/master/packages/svg-baker/test/transformations/prefix-style-selectors.test.js) and [here](https://travis-ci.org/kisenka/svg-baker/builds/228011253#L289) you can check that it's passed. I've update svg-baker version in svg-sprite-loader@2.0.4, please check!

**Comment by briantobo** [comment]
Version 2.0.4 fixes it for me.
Thanks again !
